<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH="100%" HEIGHT="15" BGCOLOR="#000000" ><TR>
<TD><CENTER><A HREF="http://www.emerg-med.com" TARGET="_blank" onmouseover="imgOn('img10')" onmouseout="imgOff('img10')"><IMG SRC="images/footeri.gif" NAME="img10" ALT="www.emerg-med.com" BORDER=0 HEIGHT=15 WIDTH=200 ALIGN=BOTTOM></A></CENTER></FONT></TD></TR></TABLE>
</BODY>
</HTML>
<?php 
ob_end_flush(); 
?>