<?php
$Title="Background";
$Text="
The aim of the meditute project is to develop, deliver and monitor the use of  high quality, <B>freely distributable</B> medical education material to hospital staff using the hospital's intranet system, or the internet.<BR>
<BR>
Meditute uses an open-source/ open peer review development method that has been successfully used for software development e.g. Linux.<BR>
<BR>
The project currently has doctors and nurses working on tutorial development, but it is hoped to include other health professionals and patient groups in the future. As such it represents true inter-disciplinary/ inter-professional learning.<BR>
<BR>
Meditute uses a Linux based open-source infrastructure to assure the most secure and reliable delivery system. This means that a hospital/ medical/ nursing/ para-medical institutions will be able to set up a complete system without having to pay for expensive hardware/ software. As such it will be a valuable contribution to medical education in both developed and developing countries.<BR>
<BR>
The meditute system is currently in pilot testing in Ballarat, near Melbourne, Australia.
";
?>