<?php
$Title="Patient Billing";
$Text="
For Australian use, there is a billing module included. Ticking boxes on the 'standard' form results in the appropriate amount from the Medicare Benefits Schedule being added to the bill. In addition there is the a facility to add any other procedures from the MBS to the bill.<BR>
<BR>
Other billing schedules can be easily substituted.<BR>
<BR>
The hospital logo is incorporated in the bill.<BR>
<BR>
The facility fee may be easily changed by the user.<BR>



";
?>