<?php
$Title="Emergency data collection";
$Text="
Data collection is necessary for monitoring and planning emergency services provision.<BR>
<BR>
Data can be collected or packaged in any format, although current support is for the VEMD dataset. This is an internationally recognised dataset, incorporating ICD10 diagnoses and a validated injury monitoring dataset.<BR>
<BR>
Poor quality interface design results in poor quality data. The design of emerg-med validates data before patients can be discharged.<BR>

<BR>
";
?>