<?php
$Title="Decision Support";
$Text="
Decision support is an important, customisable feature built into the emerg-med interface. It is done carefully, in order to support rather than dictate, practice.<BR>
<BR>
<H3>Nursing Decision Support</H3>
Triage support is contained in flow diagrams derived from the Manchester Triage group. These may be customised by the user using the built in templates, or users can build their own new templates.
<BR>
<H3>Medical Decision Support</H3>
Medical decision support includes protocols/guidelines, patient handouts, and 



";
?>