<?php
$Title="Development";
$Text="
The Australian Medical Training Review Panel (1996) recognised that learning in the immediate postgraduate period was important, and needs to be supported. It did not give any specific guidelines as to how it should take place, but specified that documentation of learning was important, and that innovative projects should be supported.<BR>
<BR>
A major review in  the UK by the <A HREF=\"javascript:popupwindow('http://www.gmc-uk.org/med_ed/sho.htm#programmes');\">General Medical Council (1998)</A> into the immediate postgraduate years identified four specific modes of learning:
<UL>
<LI>Formal educational opportunities - e.g. lectures/ clinical meetings
<LI>Study leave, to encourage attendance at courses.
<LI>Practice based learning: creating a culture of the 'adult learner' (Knowles, 1990) with self-directed cycles of action / reflection / learning.
<LI>Brief learning materials.
</UL>
<B>Brief Learning Materials</B><BR><BR>
The brief learning materials are a paper-based short tutorial, usually initiated by the junior doctor's peers. Unfortunately their uptake has not been as wide as had been hoped.<BR>
<BR>
Factors limiting their use have been:<UL>
<LI>the need for the learner (the junior doctor) to have to carry around multiple thick books of educational topics.
<LI>it is difficult and time consuming to monitor their use.
<LI>the need for a 'champion' to generate enthusiasm and support for their ongoing use.
<LI>they tend to be initiated by the peer, rather than being truly self-directed.
<LI>validation of content takes a long time.
<LI>the long feedback loop in developing/ refining the educational material means they are expensive to update.
<LI>the limited range of educational material that can be presented.
<LI>the expense of developing, printing, and distributing the manuals.
</UL>
Meditute solves the above problems by<UL>
<LI>delivering multimedia content using an intranet, integrating monitoring, and making available 24/7/365.
<LI>producing a document summarising learning which can be produced at the end of the junior's term at the institution.
<LI>using a open source software development model to generate and validate the meditutes, the essence of which is that \"with many eyeballs, all problems are spotted\".
<LI>using open source software, so that all the content and all the software necessary to run it can be freely distributed.
</UL>";
?>