<?php
$Title="How free is free?";
$Text="
When we talk about 'free' software, we are talking about free as in 'free speech', not free as in 'free beer'.<BR>
<BR>
All meditute software and content is copyright.<BR>
<BR>
The meditute <B>system</B> is licensed under the meditute licence [based on the old MySQL licence]. For a copy of the licence, see above under \"Licence\" however in essence the rules are:<BR>
<UL>
<LI>Most people and organisations (whether public or private) will be able to use the program without paying anything.<BR><BR>
<LI>You only <B><I>have</I></B> to buy a license if money changes hands e.g. an external organisation is providing a support contract.
</UL><BR>
Naturally we hope organisations will buy a licence to support a worthwhile project, and in return will receive support and regular updates.<BR>
<BR>
The meditute <B>content</B> is licensed under the <A HREF=\"javascript:popupwindow('http://www.opensource.org');\">General Public License</A>. This grants anyone a licence to use the software, even to modify it and redistribute it, provided that it is done so under the terms of the GPL.";
?>