<?php
$Title="Meditute - goals";
$Text="
<B>2002</B><BR>
<BR>
The goals of the team are to complete a pilot project to:<OL>
<LI>refine the meditute system design.
<LI>develop a core range of meditutes for a small-medium sized hospital.
</OL>
A significant part of this phase will be a formal assessment of the system's benefits, and how it documents learning.<BR>
<BR>
<B>2003</B><BR>
<BR>
If the initial pilot is successful, we have had interest in initiating further trials in Australia, the UK and elsewhere. Please contact us if you would like to be considered for this.
";
?>