<?php
$Title="Meditute - how you can help";
$Text="
<B><I>The touchstone of knowledge is the ability to teach</I> - Aristotle.</B><BR>
<BR>
If you have an idea for a meditute, you can set up an account, log in, and start work on your meditute. Alternatively, you can download the development pack so you can work offline.<BR>
Meditutes which have not been formally approved are stamped 'DRAFT'.<BR>
<BR>
You have complete control over the meditute, but everyone can see your work, and can make suggestions to you  If they like it, they will give it approval 'points'.<BR>
<BR>
When you have finished your meditute, and enough people have seen it and approved it, you can submit it for inclusion in the main database.<BR>
<BR>
The more meditutes you write, the more approval points you get, so that your approval means more to those meditutes you give it to.<BR>
You can have as many meditutes in progress as you have points.<BR>
By submitting material to meditute.org, you agree that:<UL>
<LI>this is your own work
<LI>no one but you has copyright of the content
<LI>you allow others to use it freely under the terms of the <A HREF=\"javascript:popupwindow('http://www.opensource.org');\">GPL</A>.
</UL>

<B>Graphics</B>
<BR>
Drawings and pictures are important. They can be added to the meditute once it has gained 40 points.<BR>
If you cannot find a good picture, say what you want and someone may suggest one, or we may be able to find one on our database.<BR>Stick drawings of people are often effective to make simple points.<BR>
<BR>
For more details, download these documents:<BR>
<A HREF=\"javascript:popupwindow('../meditute/documents/writing_meditutes.pdf');\">Writing a Meditute<IMG SRC=\"images/pdf.gif\" ></A> (45kb)<BR>
<A HREF=\"javascript:popupwindow('../meditute/documents/meditute_template.pdf');\">Meditute Template<IMG SRC=\"images/pdf.gif\" ></A> (25kb)<BR>

";
?>