<?php
$Title="System Integration";
$Text="
<H3>Industry Standard SQL</H3>
The emerg-med system runs under linux and uses standard SQL databases. In addition to the built-in reporting, the data can be extracted easily using standard industry tools.<BR>
<BR>
Web-based interfaces are the standard for user-friendly data entry. This means reduced training time, and increased productivity. The look and feel can be changed to suit any environment.<BR>



";
?>