<?php
$Title="Why buy a licence";
$Text="
People and organisations who make money out of using/ supporting meditute <I>have</I> to buy a licence.<BR>
<BR>
Others do not have to buy a licence. Good reasons to buy a licence are:
<UL>
<LI>You want a full copy of all the software and tutorials sent to you by express mail.
<LI>You want your meditutes updated quarterly.
<LI>You want to support the costs of developing the software and content, and running the website.
</UL>

For licencing enquiries, use the contact form on the menu bar above.

";
?>