<?php
$Title="Progress";
$Text="
<B>January 2003</B><BR>
The version 2.0 of the meditute server is available for download.<BR>
<BR>


<B>November 2002</B><BR>
The version 2.0 of the meditute server will be available for downloading soon. The internet version of meditute will be launched then, with as many meditutes as we have.<BR>
Content is being added daily, and we are up to 20 meditutes.<BR>
<BR>
<B>August 2002</B><BR>
Equipment has arrived, the server has been set up. The testing phase is beginning, with 10 meditutes being available at the end of the month.<BR>
A <A HREF=\"javascript:popupwindow('http://iet.open.ac.uk/oucem/AboutUs/News/NewsletterJune02.pdf');\">piece about the meditute project</A> (423kb) appeared in the <A HREF=\"javascript:popupwindow('http://iet.open.ac.uk/oucem/index.htm');\">Open University Centre Education in Medicine</A> newsletter.<BR>
<BR>
<B>June 2002</B><BR>
An office has been set up and equipment has been ordered. Needs analysis is continuing, using structured interviews.<BR>
<BR>
<B>May 2002</B><BR>
A beta (test) system is available on the website. At present this does not allow editing of the tutorials, but demonstrates some of the technology.<BR>
There are still a few bugs- if you have finished the meditute, and want to start again, it is best to close all browser windows and start again.<BR>
<BR>
<B>April 2002</B><BR>
<A HREF=\"javascript:popupwindow('http://iet.open.ac.uk/oucem/index.htm');\">The Open University Centre Education in Medicine</A> have very kindly donated content from their service based learning (SBL) material to be used to develop further meditutes. This is a bold and imaginative step, and we are very grateful for their contribution.<BR>
<BR>
<B>March 2002</B><BR>
The leaders of the meditute project were delighted to receive the maximum grant from the <A HREF=\"javascript:popupwindow('http://www.pmcv.com.au');\">Postgraduate Medical Council of Victoria</A> (the only project to do so in 2002).<BR>
This funding enables a development of a core content of about 200 meditutes. Grant applications for development of meditutes for other specific groups are in progress.<BR>
For more details, see the <A HREF=\"javascript:popupwindow('download/meditutePMCV.pdf');\">submission<IMG SRC=\"images/pdf.gif\" ></A> (40 kb)<BR>



";
?>