<?php
$Title="Real time data";
$Text="
<BR>
Emergency clinicians find it frustrating that managers do not understand the workflow in emergency departments.<BR>
Managers find it frustrating that they do not find out about problems with bed/service provision until it is too late. They are forced to manage reactively rather than pro-actively.<BR>

<BR>
The major advance in manufacturing and service industries over the past 20 years has been the 'just-in-time' matching of resources and need. This enables a flexible response and early service planning, while tying up the minimum of resources. Without this information, managers are just spectators, and are powerless to enable the hospital to cope with variations in demand.<BR>
<BR>
Emerg-med solves this problem by making this data available in real-time in a variety of formats - e.g. XML/ or as web pages, which can be uploaded over secure internet links to a central server. This means that it is possible to monitor emergency service usage in real-time, enabling pro-active service provision, rather than just reacting to problems after they occur.<BR>
<BR>
As emerg-med is free, using it over many emergency departments, each updating a central server can make it easy to predict where and when extra services will be needed.<BR>



";
?>