<?php
$Title="Recommended system specifications";
$Text="
We recommend running RedHat Linux 7.3 on a Pentium with 256MB of RAM.<BR>
<BR>
The minimum system is a 486 with 64 MB RAM. RAM is more important than processor speed. You are unlikely to notice any speed difference between a Pentium I and Pentium IV. <BR>AMD processors can be used, but Intel processors are generally more Linux-friendly.<BR><BR>
Network card 10/100 - 3COM or Intel are most Linux-friendly.<BR>
Hard disk: > 4 GB <BR>
CDROM drive (can be removed after software installation if necessary)<BR>
<BR>
We recommend ex-office Pentium II machines as they have video and network cards on board, use cheap SDRAM, and are generally fairly robust, common and cheap (USD 100).<BR>
<BR>
";
?>