<?php
$Title="How it works";
$Text="
The web pages you see are not stored as web pages: every web page you see is constructed at that time using the most up-to-data information from a database.<BR>
<BR>
What this means is that anyone can write a meditute. You do not have to have any special skills. To make it even easier, we have a development pack which you can download for free which allows you to write the whole tutorial on your computer. Then, when you are online, you can upload it to meditute.<BR>
<BR>
The meditute server runs on Linux, the freely available operating system which is faster and more stable than other well known alternatives.<BR>
<BR>
The system uses a web server (Apache) which combines information from the a database (MySQL) to make web pages. A language called PHP controls the whole process.<BR>
<BR>
As all the software to run meditute is freely available and easy to set up, any organisation can set up a meditute webserver at minimal cost (USD 100 for hardware).
";
?>