<?php
$Title="What does the server do?";
$Text="
The meditute webserver you can download is a copy of the webserver at meditute.org.<BR>
When you type 'meditute' into your web browser, <B><I>your</I></B> server makes the webpages, instead of meditute.org.<BR>
<BR>
[The webpages have to be made up every time you see them as, unlike a non-interactive site, they are stored on a database, along with all the results.]<BR>
<BR>
The advantage of this is <I><B>speed</B></I> - instead of having to travel over the internet, which is slow, the webpages, pictures and even video appear instantly.<BR>
<BR>
You can customise the tutorials to your own institution.<BR>

<BR>
A competent computer department should be able to set up your own server in about two hours, using the instructions provided.<BR>



<BR>
In the future, the meditute webserver on your network will be able to automatically update itself with the latest meditutes. 



";
?>