<?php
$Title="Server FAQ";
$Text="
<H4>Q: I can't set up my server- can you help?</H4>
A: Meditute.org does not offer support in Linux loading and configuration unless you licence a copy of the meditute software.<BR>
If you require support for this, buy a retail copy of RedHat, and this will enable you to obtain such support.<BR>
<BR>
<BR>
<H4>Q: Can you run meditute on Windows?</H4>
A: Can you can convert a Ferrari to run on diesel?<BR>
<BR>
The answer to both these questions is yes it can be done, but it's missing the point somewhat.<BR>
Not recommended, and no support is offered.<BR>
<BR>
<BR>
<H4>Problems with meditute software</H4>
If there is a problem/ improvement you would like to see in the meditute software that you would like to let us know about, use the <A HREF=\"javascript:popupwindow('./wwwdisplay.php?text=contact');\">contact page</A> to tell us.<BR>
<BR>



";
?>