<?php
$Title="Server download";
$Text="

If you have not set up a linux system before, it will be helpful to have someone with you who has.<BR>
If you used computers pre-Windows and are familiar with a command line interface, you should give it a try armed with a good guide e.g. M.Kabir's guide to RedHat Linux 6 Server (ISBN 0764533371)<BR>
<BR>
<FONT COLOR=\"FF0000\"><B>Support and Configuration of RedHat.</B><BR>
Meditute.org does not offer support in RedHat loading and configuration unless you licence a copy of the meditute software.<BR>
If you require support for this, buy a retail copy of RedHat, and this will enable you to obtain such support.</FONT><BR>
<BR>

Good luck.<BR>Use the <A HREF=\"javascript:popupwindow('./wwwdisplay.php?text=contact');\">contact page</A> to let us know how it goes. Suggestions for future versions gratefully received.<BR>
<BR>
<A HREF=\"./download/meditute_server.zip\"><IMAGE SRC=\"./images/zip.gif\" ></A>&nbsp;&nbsp;<A HREF=\"./download/meditute_server.zip\">Download meditute server</A>




";
?>