<?php
$Title="Meditute Setup";
$Text="
Meditute runs on Linux. Linux is a very stable, secure and versatile operating system. It is also free.<BR>
All the necessary software to run this system can be downloaded from the internet for free.<BR>
<BR>
Although RedHat Linux is fairly straightforward to install with the instructions below, if you have not used Linux before, it's a good idea to find someone to help you.<BR>
<BR>
Detailed setup instructions are contained in the pdf file below.<BR>
[This is version 2, and has been tested quite thoroughly, but ideas for revisions are welcome].<BR>
<BR>
<A HREF=\"javascript:popupwindow('./download/meditute_setup.pdf');\">Setup<Image SRC=\"images/pdf.gif\"></A> (35kb)";
?>