<?php
$Title="Waiting room display";
$Text="
One of the main anxieties of waiting patients is the uncertainty of where they are in the queue. The constant questioning is also extremely frustrating and wearing for nursing staff.<BR>
<BR>
By providing a real-time display for patients, emerg-med prevents this anxiety. This helps to reduce the number of patients who do not wait to be seen (reducing risk), and increases patient satisfaction with their wait. By making patients aware of their position in the queue it also avoids wasting medical time calling patients who are not there.<BR>
<BR>
Anonymity is preserved by only using the patient's initials. A message for waiting patients can be updated as necessary e.g. to warn them that there has been a serious accident, and that staff are busy with this.<BR>
<BR>
";
?>