<?php
$Title="Open Source Software";
$Text="
The open source software movement is an affiliation of programmers commited to making good quality software freely available.<BR>
<BR>
The basic idea behind open source is very simple: When programmers can read, redistribute, and modify the source code for a piece of software, the software evolves. People improve it, people adapt it, people fix bugs. And this can happen at a speed that, if one is used to the slow pace of conventional software development, seems astonishing.<BR>
<BR>
The most spectacular successes of the open software movement are the operating system Linux, and the web serve Apache which together power most of the web sites on the internet.<BR>
Their success is due to the fact that they are reliable, secure, have good performance, and do not cost anything to use.<BR>
<BR>
Meditute aims to use the same principles to develop medical education content, and meditute software and content is open source - you can use it without paying anything, subject to agreeing to the licence.<BR>
<BR>
<B>So it's free?</B><BR>
<BR>
No. And yes. It is free as in 'Free Speech', not as in 'free beer'. See the 'how free is free?' section.
 
";
?>