<?php
#### remember that all references in this file are relative to the java file which executes it

print "<TR><TD VALIGN=top>";

print "<applet codebase='./emerg-med/java' Code=apPopupMenu Archive= apPopupMenu.jar Width=100% Height=20 MAYSCRIPT>
<param name=\"key\" value=\"fohsi0ngg/ern\">
<param name=\"Copyright\" value=\"Apycom Software - www.apycom.com\">
<param name=\"isHorizontal\" value=\"true\">
<param name=\"overSound\" value=\"pix/bell.au\">
<param name=\"clickSound\" value=\"pix/kap2.au\">
<param name=\"systemSubFont\" value=\"false\">
<param name=\"solidArrows\" value=\"true\">
<param name=\"buttonType\" value=\"1\">
<param name=\"status\" value=\"link\">
<param name=\"alignText\" value=\"left\">

<param name=\"backColor\" value=\"003399\">
<param name=\"backHighColor\" value=\"FFCC00\">
<param name=\"fontColor\" value=\"CCCCFF\">
<param name=\"fontHighColor\" value=\"000000\">

<param name=\"font\" value=\"Arial,12,1\">";

print "<param name=\"menuItems\" value=\"

{home,../../index.php,_self}


{emerg-med.com}

{|features}
{||emergency medicine data collection,../../wwwdisplay.php?text=datacollection,_self}
{||real-time information for managers,../../wwwdisplay.php?text=realtime,_self}
{||system integration,../../wwwdisplay.php?text=integration,_self}
{||billing,../../wwwdisplay.php?text=billing,_self}
{||patient notes,../../wwwdisplay.php?text=notes,_self}
{||decision support,../../wwwdisplay.php?text=decisionsupport,_self}
{||GP letters,../../wwwdisplay.php?text=gpletter,_self}
{||waiting room,../../wwwdisplay.php?text=waitingroom,_self}
{||expected patients,../../wwwdisplay.php?text=expected,_self}

{|emerg-med system}
{||what does it do?,../../wwwdisplay.php?text=serverwhat,_self}
{||how does it work?,../../wwwdisplay.php?text=serverwork,_self}
{||why was it developed,../../wwwdisplay.php?text=developed,_self}
{||system requirements,../../wwwdisplay.php?text=req,_self}
{||system setup,../../wwwdisplay.php?text=setup,_self}
{||download now,../../wwwdisplay.php?text=serverdl,_self}

{|about us}
{||background,../../wwwdisplay.php?text=background,_self}
{||goals,../../wwwdisplay.php?text=goals,_self}
{||progress,../../wwwdisplay.php?text=progress,_self}

{|contact}
{||contact meditute.org,../../wwwdisplay.php?text=contact,_self}

{demonstration}
{|try it now,../index.php,_emerg}


{FAQ}
{|how much does it cost?}
{||open source software,../../wwwdisplay.php?text=oss,_self}
{||why use open source?,../../wwwdisplay.php?text=whyoss,_self}
{||how free is free?,../../wwwdisplay.php?text=free,_self}
{||licence,../../wwwdisplay.php?text=licence,_self}
{||why buy a licence,../../wwwdisplay.php?text=licencewhybuy,_self}

{|system FAQ}
{||emerg-med system on windows,../../wwwdisplay.php?text=serverfaq,_self}
{||I can't set up emerg-med,../../wwwdisplay.php?text=serverfaq,_self}
{||problems with emerg-med,../../wwwdisplay.php?text=serverfaq,_self}



\"></applet>\n";

print "</TD></TR>";


?>