<?php // loginform.inc ?>
<FORM ACTION="https://toshiba/meditute/admin.php" METHOD="post">
<CENTER>
<TABLE width=300 border=0 >
<TR><TD><CENTER>
<BR><font face=Arial, Helvetica size=5>
Login Screen<BR>
<BR></CENTER>
</TD></TR><TR><TD>
<CENTER>
<TABLE BORDER="5">
<TR>
<TD><font face=Arial, Helvetica size=4>username</FONT></TD>
<TD>
<INPUT TYPE="text" NAME="username" SIZE="12" MAXSIZE="10">
</TD>
</TR>
<TR>
<TD><font face=Arial, Helvetica size=4>password</FONT></TD>
<TD>
<INPUT TYPE="password" NAME="password" SIZE="12" MAXSIZE="10">
<INPUT TYPE="hidden" NAME="login" VALUE = "Y">
</TD>
</TR>
<TR>
<TD COLSPAN="2" ALIGN="center">
<INPUT TYPE="submit" VALUE="Submit">
</TD>
</TR>
</TABLE>
</CENTER>
</TD></TR>
</TABLE>
</CENTER>
</FORM><BR><BR><BR>