CREATE TABLE `ED`.`UDDA` (
  `key_ID` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UDDAUniqueID` BIGINT(10) UNSIGNED NOT NULL DEFAULT 0,
  `Primary` TINYTEXT NOT NULL DEFAULT '',
  `Secondary` TINYTEXT NOT NULL DEFAULT '',
  `Diagnosis` TINYTEXT NOT NULL DEFAULT '',
  `SearchTerms` TINYTEXT NOT NULL DEFAULT '',
  `ICD10Code` TINYTEXT NOT NULL DEFAULT '',
  PRIMARY KEY(`key_ID`)
)
TYPE = InnoDB;